### PR TITLE
Refresh Main View Feature

### PR DESCRIPTION
**Pull request by reganq**
Added a refresh feature, which can be called to put postview and barview into a default state. Also, had to change filter post use case a little bit so also fixed its tests.

### CODE REVIEW

**Review by sushimon — DISMISSED** [review]

**Review by izumidayo — DISMISSED** [review]
Maybe implement Richard's changes first but everything else looks good to me!

**Review by Thehashhobo — APPROVED** [review]
lgtrm

**Review by JohannLeidenfrost — APPROVED** [review]
Lgtm

**Review by sushimon — APPROVED** [review]
Previous comments were addressed. Looks good to merge.

**Pull request merged**
