### PR TITLE
Updating User's listPosts column when a new post is made.

### PR DESCRIPTION
**Pull request by JohannLeidenfrost**
The tests have been adjusted accordingly.

### CODE REVIEW

**Review by reganq — DISMISSED** [review]
looks good!

**Review by Thehashhobo — DISMISSED** [review]
lgtm

**Review by izumidayo — DISMISSED** [review]
Looks good to me!

**Review by sushimon — APPROVED** [review]
No glaring issues, looks good to merge.

**Review by reganq — APPROVED** [review]
looks good!

**Review by reganq — APPROVED** [review]
lgtm

**Review by sushimon — APPROVED** [review]

**Review by izumidayo — APPROVED** [review]
Looks good to me!

**Pull request merged**
