### PR TITLE
Display Favourited Posts and My Posts

### PR DESCRIPTION
**Pull request by izumidayo**
- played around with filter post data access and interactor so that a user can search for their own posts and favourited posts
- work to be done would be updating filter post testing and condensing the code in the filter post interactor class so we dont have as much duplicate code

### CODE REVIEW

**Review by Thehashhobo — APPROVED** [review]
looks good, I was under the impression that picking out individual data from csvs should be done in the interactor but it shouldn't matter.

**Review by reganq — DISMISSED** [review]
approving!

**Review by BerryRahul — DISMISSED** [review]
looks good!

**Review by BerryRahul — APPROVED** [review]

**Review by reganq — APPROVED** [review]
approved

**Review by Thehashhobo — APPROVED** [review]
lgtm

**Pull request merged**
